-- Lost in Translation — seed idioms (48 entries, all <= 120 chars).
-- Idioms are the best seeds: literal translation destroys them.
-- Import AFTER schema.sql:
--   /opt/lampp/bin/mysql -u root -p lost_in_translation < seeds.sql

USE lost_in_translation;

INSERT INTO seeds (text) VALUES
('It''s raining cats and dogs'),
('Break a leg'),
('The early bird catches the worm'),
('He let the cat out of the bag'),
('Bite the bullet'),
('Speak of the devil'),
('The ball is in your court'),
('Barking up the wrong tree'),
('A blessing in disguise'),
('Beat around the bush'),
('Cut corners'),
('Burn the midnight oil'),
('Once in a blue moon'),
('A piece of cake'),
('Kill two birds with one stone'),
('Under the weather'),
('The last straw'),
('Cost an arm and a leg'),
('Hit the nail on the head'),
('Spill the beans'),
('Add fuel to the fire'),
('Judge a book by its cover'),
('Every cloud has a silver lining'),
('Curiosity killed the cat'),
('Actions speak louder than words'),
('Don''t count your chickens before they hatch'),
('The grass is always greener on the other side'),
('When pigs fly'),
('A penny for your thoughts'),
('Let sleeping dogs lie'),
('Pull yourself together'),
('Throw in the towel'),
('Wrap your head around it'),
('Miss the boat'),
('On thin ice'),
('The tip of the iceberg'),
('A storm in a teacup'),
('Steal someone''s thunder'),
('Go the extra mile'),
('Jump on the bandwagon'),
('Cry over spilled milk'),
('Face the music'),
('Wear your heart on your sleeve'),
('Caught between two stools'),
('A hot potato'),
('Cutting it close'),
('The best of both worlds'),
('Not my cup of tea');
